# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    
    environment:
      name: PROD
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Env file
      run: |
        touch .env
        echo POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" >> .env
        echo POSTGRES_PASS="${{ secrets.POSTGRES_PASS }}" >> .env
        echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> .env
        echo POSTGRES_DB_NAME="${{ secrets.POSTGRES_DB_NAME }}" >> .env
        echo MONGO_URI="${{ vars.MONGO_URI }}" >> .env
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build
      run: go build -v ./

    - name: Restart service
      run: systemctl restart factured-reception-backend.service
